root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main.exe ./cmd"
  stop_exec = ["tmp/main.exe"]

[[watcher]]
  path = "cmd"
  build_args = ["-tags", "debug"]
  exclude_dirs = ["tmp", "vendor"]

[[watcher]]
  path = "pkg"
  build_args = ["-tags", "debug"]
  exclude_dirs = ["tmp", "vendor"]

[log]
  mode = "file"